# Generated by Django 4.0 on 2024-08-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'ordering': ['id'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
