
//=========TYPES REDUX ================
//=====================================
//==============Authemtication================

export const SIGNUP_SUCCES = 'SIGNUP_SUCCES';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';

export const LOGOUT = 'LOGOUT';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';

//=================blog===================
//category
export const GET_CATEGORYLIST_SUCCESS = 'GET_CATEGORYLIST_SUCCESS';
export const GET_CATEGORYLIST_FAIL = 'GET_CATEGORYLIST_FAIL';
export const GET_BLOGLIST_OF_CATEGORY_SUCCESS = 'GET_BLOGLIST_OF_CATEGORY_SUCCESS'; 
export const GET_BLOGLIST_OF_CATEGORY_FAIL = 'GET_BLOGLIST_OF_CATEGORY_FAIL';
export const GET_BLOGLIST_POST_SUCCESS = 'GET_BLOGLIST_POST_SUCCESS'; 
export const GET_BLOGLIST_POST_FAIL = 'GET_BLOGLIST_POST_FAIL';
export const GET_POST_DETAIL_SUCCESS = 'GET_POST_DETAIL_SUCCESS'; 
export const GET_POST_DETAIL_FAIL = 'GET_POST_DETAIL_FAIL';

//================userprofile==================
export const GET_PROFILE_USER_VIEW_SUCCESS = 'GET_PROFILE_USER_VIEW_SUCCESS';
export const GET_PROFILE_USER_VIEW_FAIL = 'GET_PROFILE_USER_VIEW_FAIL';
export const GET_PROFILE_USER_UPDATE_SUCCESS = 'GET_PROFILE_USER_UPDATE_SUCCESS'  
export const GET_PROFILE_USER_UPDATE_FAIL = 'GET_PROFILE_USER_UPDATE_FAIL'

//================profileutilities=================
export const GET_PROFILE_UTILITIES_SAVEPOST_SUCCESS = 'GET_PROFILE_UTILITIES_SAVEPOST_SUCCESS'
export const GET_PROFILE_UTILITIES_SAVEPOST_FAIL = 'GET_PROFILE_UTILITIES_SAVEPOST_FAIL'
export const GET_PROFILE_UTILITIES_VIEWPOST_USER_SUCCESS = 'GET_PROFILE_UTILITIES_VIEWPOST_USER_SUCCESS'
export const GET_PROFILE_UTILITIES_VIEWPOST_USER_FAIL = 'GET_PROFILE_UTILITIES_VIEWPOST_USER_FAIL'
export const GET_PROFILE_UTILITIES_DELETEPOST_USER_SUCCESS = 'GET_PROFILE_UTILITIES_DELETEPOST_USER_SUCCESS' 
export const GET_PROFILE_UTILITIES_DELETEPOST_USER_FAIL = 'GET_PROFILE_UTILITIES_DELETEPOST_USER_FAIL'

//===================Contact================================
//export const GET_CONTACT_SEND_MAIL_SUCCESS = 'GET_CONTACT_SEND_MAIL_SUCCESS'
//export const GET_CONTACT_SEND_MAIL_FAIL = 'GET_CONTACT_SEND_MAIL_FAIL'